language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements.ini
# command to run tests
script:
  - locust -f ./example/locust/test_http.py --conf ./example/locust/host.conf