FROM apulistech/ubuntu:18.04-python375-withtools
WORKDIR /usr/local/Ascend

COPY ./Ascend/  /usr/local/Ascend/
COPY tensorflow-1.15.0-cp37-cp37m-linux_aarch64.whl .
COPY slog.conf .

RUN pwd && ls -la /usr/local/Ascend/
RUN pip3.7 list
RUN pip3.7 install  --upgrade pip
RUN pip3.7 install  ./tfplugin/latest/arm64-linux_gcc7.3.0/tfplugin/bin/npu_bridge-1.15.0-py3-none-any.whl
RUN pip3.7 install  ./nnae/latest/arm64-linux_gcc7.3.0/fwkacllib/lib64/hccl-0.1.0-py3-none-any.whl
RUN pip3.7 install  ./nnae/latest/arm64-linux_gcc7.3.0/fwkacllib/lib64/te-0.4.0-py3-none-any.whl
RUN pip3.7 install  ./nnae/latest/arm64-linux_gcc7.3.0/fwkacllib/lib64/topi-0.4.0-py3-none-any.whl
RUN pip3.7 install  ./tensorflow-1.15.0-cp37-cp37m-linux_aarch64.whl

# The root directory of run package
ENV LOCAL_ASCEND=/usr/local/Ascend

# Lib libraries that the run package depends on
ENV LD_LIBRARY_PATH=\
/usr/lib/aarch64-linux-gnu/hdf5/serial:\
${LOCAL_ASCEND}/add-ons:\
${LOCAL_ASCEND}/nnae/latest/arm64-linux_gcc7.3.0/fwkacllib/lib64:\
${LOCAL_ASCEND}/driver/lib64/common:\
${LOCAL_ASCEND}/driver/lib64/driver:\
/usr/local/lib\:\
/usr/lib/:\
/lib
# Environment variables that must be configured
# TBE operator implementation tool path
ENV TBE_IMPL_PATH=${LOCAL_ASCEND}/ascend-toolkit/latest/arm64-linux_gcc7.3.0/opp/op_impl/built-in/ai_core/tbe

# TBE operator compilation tool path
ENV PATH=${LOCAL_ASCEND}/ascend-toolkit/latest/arm64-linux_gcc7.3.0/fwkacllib/ccec_compiler/bin/:${PATH}

# Python library that TBE implementation depends on
ENV PYTHONPATH=${TBE_IMPL_PATH}:${PYTHONPATH}
ENV ASCEND_OPP_PATH=/usr/local/Ascend/ascend-toolkit/latest/arm64-linux_gcc7.3.0/opp
