
FROM ubuntu:18.04
WORKDIR /home/docker-build/

RUN apt-get update && apt install ca-certificates -y

RUN echo "deb  https://repo.huaweicloud.com/ubuntu-ports/ bionic main restricted universe multiverse" >/etc/apt/sources.list && \
    echo "deb-src   https://repo.huaweicloud.com/ubuntu-ports/ bionic main restricted universe multiverse" >>/etc/apt/sources.list && \
    echo "deb  https://repo.huaweicloud.com/ubuntu-ports/ bionic-security main restricted universe multiverse" >>/etc/apt/sources.list && \
    echo "deb-src  https://repo.huaweicloud.com/ubuntu-ports/ bionic-security main restricted universe multiverse" >>/etc/apt/sources.list && \
    echo "deb  https://repo.huaweicloud.com/ubuntu-ports/ bionic-updates main restricted universe multiverse" >>/etc/apt/sources.list && \
    echo "deb-src  https://repo.huaweicloud.com/ubuntu-ports/ bionic-updates main restricted universe multiverse" >>/etc/apt/sources.list && \
    echo "deb  https://repo.huaweicloud.com/ubuntu-ports/ bionic-backports main restricted universe multiverse" >>/etc/apt/sources.list

# Set timezone
RUN apt-get update -y && apt-get install -y systemd apt-utils sudo  --fix-missing
RUN echo "Asia/Shanghai" | tee /etc/timezone
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai  /etc/localtime

RUN sudo apt-get -y install build-essential libhdf5-dev pkg-config  libatlas-base-dev gfortran
RUN sudo apt-get -y install software-properties-common
RUN sudo apt-get -y install --no-install-recommends   git   mercurial   openssh-client   subversion     procps && rm -rf /var/lib/apt/lists/*
RUN sudo apt-get update && sudo apt-get -y install --no-install-recommends   ca-certificates   curl   netbase   wget  && rm -rf /var/lib/apt/lists/*
RUN sudo apt-get update && apt-get -y install libhdf5-serial-dev python-tables python3-dev

# Install net-tools
RUN ln -s /lib /lib64
RUN apt-get update && apt-get install -y net-tools
RUN apt-get install -y iproute2
RUN apt-get install openssl -y
RUN apt-get install vim -y

# Install python3.7.5
RUN sudo apt-get update && apt-get -y install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev wget libbz2-dev
RUN  wget https://www.python.org/ftp/python/3.7.5/Python-3.7.5.tgz --no-check-certificate
# For faster build time, modify the -j flag according to your processor. If you do not know the number of cores your processor, you can find it by typing nproc
RUN tar -xf Python-3.7.5.tgz && cd Python-3.7.5 && ./configure --enable-shared --enable-universalsdk --enable-optimizations && make -j 192 && make altinstall
RUN cp Python-3.7.5/libpython3.7m.so.1.0 /usr/lib
RUN cp Python-3.7.5/libpython3.7m.so /usr/lib
RUN cp Python-3.7.5/libpython3.so /usr/lib
RUN pip3.7 config set global.index-url https://mirrors.aliyun.com/pypi/simple

RUN sudo apt-get -y install python3.7-dev 

# Install py-tools
RUN pip3.7 install --upgrade pip
RUN pip3.7 install tensorboard && \
    pip3.7 install numpy && \
    pip3.7 install decorator && \
    pip3.7 install sympy==1.4 && \
    pip3.7 install cffi==1.12.3 && \
    pip3.7 install pyyaml && \
    pip3.7 install pathlib2 && \
    pip3.7 install grpcio && \
    pip3.7 install grpcio-tools && \
    pip3.7 install protobuf && \
    pip3.7 install scipy && \
    pip3.7 install requests && \
    pip3.7 install jupyterlab && \
    pip3.7 install sympy && \
    pip3.7 install Cython
# control log level. 0-DEBUG, 1-INFO, 2-WARNING, 3-ERROR, default level is WARNING.
ENV GLOG_v=2

