FROM opensuse/leap:15.2

RUN mkdir /etc/zypp/repos.d/repo_bak && mv /etc/zypp/repos.d/*.repo /etc/zypp/repos.d/repo_bak/ && \
zypper ar -fcg https://mirrors.huaweicloud.com/opensuse/distribution/leap/15.2/repo/oss HuaWeiCloud:15.2:OSS && \
zypper ar -fcg https://mirrors.huaweicloud.com/opensuse/distribution/leap/15.2/repo/non-oss HuaWeiCloud:15.2:NON-OSS && \
zypper ar -fcg https://mirrors.huaweicloud.com/opensuse/update/leap/15.2/oss HuaWeiCloud:15.2:UPDATE-OSS && \
zypper ar -fcg https://mirrors.huaweicloud.com/opensuse/update/leap/15.2/non-oss HuaWeiCloud:15.2:UPDATE-NON-OS &\
zypper ref && zypper update && zypper install -y curl python3 &\
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3 get-pip.py && zypper install -y ansible helm openssh
